### ISSUE TITLE
vehicles can behind the border

### ISSUE THREAD

**Issue by 100petr** [yannicklamprecht/WorldBorderAPI#82] opened 2022-06-06 08:37 UTC
**Describe the bug**
I use plugin vehicles (https://www.spigotmc.org/resources/✈%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/) and itemsadder (https://www.spigotmc.org/resources/✨itemsadder⭐emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/). Both plugins have vehicles with which you can get across the border on skyblock. In support of bskyblock, they wrote me that this is a worldborder api thing. I got the same answers for itemsadder and vehicles. **So three people wrote me that there is a problem in the worldborder api**

**To Reproduce**
1. Install bentobox, bskyblock, border, worldborder api (+ia and lonelibs) - lonedev (author itemadder) may give you access to the plugin if you need it
2. Try to fly across the border with a wooden plane

**Expected behavior**
Players will not be able to cross the border with the vehicles

**Screenshots**
I don't have at the moment, but I'll send if necessary

**Additional context**
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1608

**Comment by yannicklamprecht** [comment] 2022-06-06 11:50
Not a bug. That's more of a feature request.
As I said multiple times, it is out of scope for this API.
This API is only present to show the visuals of the world border per player.

**Closed by yannicklamprecht** 2022-06-06 11:50 UTC
